resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: glue-viz
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    xvfb: true
    coverage: codecov
    libraries:
      apt:
        - libxkbcommon-x11-0
        - libgfortran5
      brew:
        - enchant

    envs:

    - linux: codestyle
      libraries: {}
      coverage: 'false'

    - linux: py36-test-casa
    - linux: py37-test
    - linux: py38-test
    - linux: py38-test-dev

    - macos: py36-test-casa
    - windows: py37-test
    - macos: py38-test
    - windows: py38-test-dev

    - linux: py36-docs
    - macos: py37-docs
    - windows: py38-test
